### ISSUE TITLE
[Anon] Bioficers: "Pretty" PDF exports each unit profile to a separate page when trying to print save as pdf.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/dropfleet-commander-2024#1]
**Problem:**
"Pretty" PDF exports each unit profile to a separate page when trying to print save as pdf.

**Expected:**
If possible, consolidation on as few pages as possible would be preferred.

**List:** https://www.newrecruit.eu/app/list/ynaud

**Comment by Kemp-J** [comment]
This can be solved via options in New Recruit when viewing the export prior to printing. Click on the setting (cog) icon at the top right and untick "One per page".
